name: Deploy Pyxel App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: python
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install SDL2 (required for Pyxel)
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-2.0-0

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: 
        run: |
          uv run pyxel package ./ plank_cat.py
          uv run pyxel app2html plank-cat.pyxapp
          sed -i 's/, gamepad: "enabled"//g' plank-cat.html
          mkdir -p dist
          mv plank-cat.html dist/index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
